---
# Source: michelson/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: michelson1
  labels:
    helm.sh/chart: michelson-0.1.0
    app.kubernetes.io/name: michelson
    app.kubernetes.io/instance: michelson1
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: michelson/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: michelson1
  labels:
    helm.sh/chart: michelson-0.1.0
    app.kubernetes.io/name: michelson
    app.kubernetes.io/instance: michelson1
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: michelson
    app.kubernetes.io/instance: michelson1
---
# Source: michelson/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: michelson1
  labels:
    helm.sh/chart: michelson-0.1.0
    app.kubernetes.io/name: michelson
    app.kubernetes.io/instance: michelson1
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 6
  selector:
    matchLabels:
      app.kubernetes.io/name: michelson
      app.kubernetes.io/instance: michelson1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: michelson
        app.kubernetes.io/instance: michelson1
    spec:
      serviceAccountName: michelson1
      securityContext:
        {}
      containers:
        - name: michelson
          securityContext:
            {}
          image: "nginx:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}

